import styled from 'styled-components'

export const Directorbackground = styled.div`
background-image: url('https://lh3.googleusercontent.com/DK762-B5fol5lvQ-OC05Aol_Dz638JdwZBIDxIc0Wd7EkPCpMzgpVDmecZmQPdb_-gjwfDdAVSC17V3UhtflFLCwRMveg6mZN5rgnE7c5C8cCznQ38EWH3FQ3sj7CkJ63d-xTnmlBSRTyX1NcOextDee68tt46HYAn4D4fT6abJS-NpfentdcP1u_C-kwYpeUwTgeghuxcTBZr8wpIh6Ae7mhfriDJioVxsgE3ezIgGaqdezZpfZDny3hjFTHC_AwnEn4FZjdEhuQBS_Wist-EeP0oKJDRAaU-nMuZs_8ukJKh1uC99sBbge7V7xZAzKkdcFLqQhLo0g_gA7Qwzoj0UrKuK2QVMShdmJOXUbhrBAmzYKWpYmZj40fcRK1sbvU9URpqRwLr3l2AVkatNNm4Zx49MqWrKSHzlurdXQfY8Cwm-jZXk5GEX6nf98totcS2fL-TAMiizhDftSr4LXvPBGc_v0VX5xfFqo9D4XCKJHxeXcPoREYWkgoGCHkUckykF_2hHul0Lk5f_vHw3Jo4eOyRfRGsunEh_evcCJp5UzHzzd-lPqWzDi2F2RdRzxbc2tBnDaG3Wph1IzLv0rybo-hNsomYlj7YhAMNtLiVYQX33ZkFe2T1mHoted3wRZeu-WoqnawrzEf9WfY4QQVEA_SwjSpLVsvQdasAwQF9pKNklHTguDwye5CnzPgybGU2IaxZnm2HZUQVG_dVT9ZBSv=w1452-h969-no?authuser=0');
height:80vh;
background-repeat:no-repeat;
background-size:cover;
background-position:center;
display:flex;
flex-direction:column;
`
export const Div = styled.div`
display:flex;
flex-wrap:wrap;
padding:100px;
gap:50px;
justify-content:space-evenly;
@media screen and (max-width:768px){
    padding:10px;
}
`